Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda
// Descrição   : estrutura de repetição
// Autor(a)    : Henrique Jose Godoy
// Data atual  : 10/12/2024
Var
// Seção de Declarações das variáveis 
crescente: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Para crescente := 1 Até 10 Faça
        Escreva(crescente, " ")
    FimPara
FimAlgoritmo