Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda
// Descrição   : estrutura de repetição
// Autor(a)    : Henrique Jose Godoy
// Data atual  : 10/12/2024
Var
// Seção de Declarações das variáveis 
decrescente: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Para decrescente := 10 Até 1 Passo -1 Faça
        Escreva(decrescente, " ")
    FimPara
FimAlgoritmo