Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda
// Descrição   : estrutura de repetição
// Autor(a)    : Henrique Jose Godoy
// Data atual  : 10/12/2024
Var
// Seção de Declarações das variáveis 
i, quadrado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Para i := 15 Até 200 Faça
        quadrado <- i * i
        Escreva("O quadrado de ", i, " é ", quadrado, "\n")
    FimPara
FimAlgoritmo