Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda
// Descrição   : Atividade de lógica de programação
// Data atual  : 4/12/2024
Var
// Seção de Declarações das variáveis 
valor, antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um valor: ")
leia(valor)
antecessor := valor - 1
escreval("O antecessor de ", valor, " é ", antecessor)
fimalgoritmo